services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back_net

  backend:
    # 1. On donne le nom de l'image (indispensable pour le CD)
    image: ghcr.io/augustinseguin/project-backend:latest
    # 2. On laisse le build en option pour le développement local
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - back_net
      - front_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    depends_on:
      - postgres

  frontend:
    image: ghcr.io/augustinseguin/project-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - front_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"                       
      - "--accesslog.format=json"            
      - "--log.level=INFO"
      - "--log.format=json"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - front_net
      - back_net

networks:
  front_net:
  back_net:

volumes:
  postgres_data: