upstream backend-blue { server backend-blue:3000; }
upstream backend-green { server backend-green:3000; }

upstream frontend-blue { server frontend-blue:80; }
upstream frontend-green { server frontend-green:80; }

server {
    listen 80;
    resolver 127.0.0.11 valid=30s;

    # ✅ On appelle le .inc (Nginx ne le chargera pas tout seul)
    include /etc/nginx/conf.d/active_target.inc;

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$target_backend;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://$target_frontend;
        proxy_set_header Host $host;
    }
}